### ISSUE TITLE
ngscopeclient crashes when an invalid path to a USBTMC instrument is given

### ISSUE THREAD

**Issue by makerprobe** [glscopeclient/scopehal-apps#559]
Rigol DS1054Z connected via external USB hub to PC
Open ngscopeclient
Menu: Add -> Oscilloscope -> Connect
![image](https://user-images.githubusercontent.com/119245350/204656139-507fbec1-f396-4807-be90-80424acc12f0.png)
Note: it should be "/dev/usbtmc1"
Click Add

Result:
```
~/scopehal-apps/build$ ./src/ngscopeclient/ngscopeclient 
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

ERROR: Couldn't open usbtmc1
Segmentation fault (core dumped)
```

From gdb:
```
$ gdb src/ngscopeclient/ngscopeclient GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from src/ngscopeclient/ngscopeclient...
(gdb) run
Starting program: /home/christoph/scopehal-apps/build/src/ngscopeclient/ngscopeclient 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
process 52297 is executing new program: /home/christoph/scopehal-apps/build/src/ngscopeclient/ngscopeclient
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea6a5640 (LWP 52301)]
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[New Thread 0x7fffe9aec640 (LWP 52302)]
[New Thread 0x7fffe92e4640 (LWP 52303)]
[New Thread 0x7fffe8ae3640 (LWP 52304)]
[New Thread 0x7fffdbfff640 (LWP 52305)]
[New Thread 0x7fffdb7fe640 (LWP 52306)]
[New Thread 0x7fffdaffd640 (LWP 52307)]
[New Thread 0x7fffda7fc640 (LWP 52308)]
[New Thread 0x7fffd9ffb640 (LWP 52309)]
[New Thread 0x7fffd97fa640 (LWP 52310)]
ERROR: Couldn't open usbtmc1

Thread 1 "ngscopeclient" received signal SIGSEGV, Segmentation fault.
0x00007ffff588247e in __GI___libc_free (mem=0x73656f6420746e65) at ./malloc/malloc.c:3368
3368	./malloc/malloc.c: No such file or directory.
(gdb) bt
#0  0x00007ffff588247e in __GI___libc_free (mem=0x73656f6420746e65)
    at ./malloc/malloc.c:3368
#1  0x00007ffff71e53be in SCPITMCTransport::~SCPITMCTransport()
     (this=0x55555666bd80, __in_chrg=<optimized out>)
    at /home/christoph/scopehal-apps/lib/scopehal/SCPITMCTransport.cpp:85
#2  0x00007ffff71e53fc in SCPITMCTransport::~SCPITMCTransport()
    (this=0x55555666bd80, __in_chrg=<optimized out>)
    at /home/christoph/scopehal-apps/lib/scopehal/SCPITMCTransport.cpp:86
#3  0x0000555555ae8187 in AddScopeDialog::DoConnect() (this=0x5555565ed0d0)
    at /home/christoph/scopehal-apps/src/ngscopeclient/AddScopeDialog.cpp:77
#4  0x0000555555ae2a8a in AddInstrumentDialog::DoRender() (this=0x5555565ed0d0)
    at /home/christoph/scopehal-apps/src/ngscopeclient/AddInstrumentDialog.cpp:123
#5  0x0000555555aefe1d in Dialog::Render() (this=0x5555565ed0d0)
    at /home/christoph/scopehal-apps/src/ngscopeclient/Dialog.cpp:80
#6  0x0000555555b32bd7 in MainWindow::RenderUI() (this=0x555556388420)
    at /home/christoph/scopehal-apps/src/ngscopeclient/MainWindow.cpp:423
#7  0x0000555555bff2e8 in VulkanWindow::Render() (this=0x555556388420)
    at /home/christoph/scopehal-apps/src/ngscopeclient/VulkanWindow.cpp:417
#8  0x0000555555b3210f in MainWindow::Render() (this=0x555556388420)
    at /home/christoph/scopehal-apps/src/ngscopeclient/MainWindow.cpp:311
#9  0x0000555555c47337 in main(int, char**) (argc=1, argv=0x7fffffffdcd8)
    at /home/christoph/scopehal-apps/src/ngscopeclient/main.cpp:125
(gdb)
```

**Comment by azonenberg** [comment]
Moving to scopehal as this is a bug in SCPITMCTransport.
